// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByolzklBD6j7JsbEGExEPR5pbUDDLRJU4',
    appId: '1:486578984214:web:5c9800dadac977a238ec37',
    messagingSenderId: '486578984214',
    projectId: 'audiobooks-b7cf9',
    authDomain: 'audiobooks-b7cf9.firebaseapp.com',
    storageBucket: 'audiobooks-b7cf9.firebasestorage.app',
    measurementId: 'G-20MRCXSW9B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOansvXF63CByBg8sc5kcHAM5YCR1AlpY',
    appId: '1:486578984214:android:19d9dc895485f1c938ec37',
    messagingSenderId: '486578984214',
    projectId: 'audiobooks-b7cf9',
    storageBucket: 'audiobooks-b7cf9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN8qoJGY3Xl0ZhZpzJr99fY5YdHDRcCDw',
    appId: '1:486578984214:ios:4da64335f7e14c0d38ec37',
    messagingSenderId: '486578984214',
    projectId: 'audiobooks-b7cf9',
    storageBucket: 'audiobooks-b7cf9.firebasestorage.app',
    iosBundleId: 'com.example.audiobooks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN8qoJGY3Xl0ZhZpzJr99fY5YdHDRcCDw',
    appId: '1:486578984214:ios:4da64335f7e14c0d38ec37',
    messagingSenderId: '486578984214',
    projectId: 'audiobooks-b7cf9',
    storageBucket: 'audiobooks-b7cf9.firebasestorage.app',
    iosBundleId: 'com.example.audiobooks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByolzklBD6j7JsbEGExEPR5pbUDDLRJU4',
    appId: '1:486578984214:web:188f21343511f4b438ec37',
    messagingSenderId: '486578984214',
    projectId: 'audiobooks-b7cf9',
    authDomain: 'audiobooks-b7cf9.firebaseapp.com',
    storageBucket: 'audiobooks-b7cf9.firebasestorage.app',
    measurementId: 'G-SH0W4C0SGC',
  );
}
